name: Actualizador de Tasas BCV

on:
  schedule:
    # Se corre a las 9:45 AM y 4:15 PM hora de Venezuela (aprox)
    - cron: '45 13 * * *'
    - cron: '15 20 * * *'
  workflow_dispatch: # Esto te permite darle a un botón para actualizar YA

jobs:
  actualizar-data:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v2

      - name: Instalar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Instalar Requests
        run: pip install requests

      - name: Correr Script
        run: python captura_bcv.py

      - name: Guardar cambios en el repo
        run: |
          git config --global user.name 'Robot-BCV'
          git config --global user.email 'robot@github.com'
          git add bancos.json
          git commit -m "Tasas actualizadas automáticamente" || echo "No hay cambios"
          git push
